-- 사용자
CREATE TABLE OUTERPARK_USER (
	USER_ID VARCHAR2(20) NOT NULL, -- 아이디,
	USER_PASSWORD CHAR(64) NOT NULL, -- 비밀번호,
	USER_NAME VARCHAR2(20) NOT NULL, -- 이름,
	USER_NICKNAME VARCHAR2(20) NOT NULL, -- 닉네임,
	USER_MAIL VARCHAR2(40) NOT NULL, -- 메일,
	USER_TYPE CHAR(8) NOT NULL -- 타입
);

-- 사용자
ALTER TABLE OUTERPARK_USER
	ADD CONSTRAINT PK_OUTERPARK_USER -- 사용자 기본키
	PRIMARY KEY (
		USER_ID -- 아이디
	);

-- 방
CREATE TABLE ROOM (
	ROOM_NUMBER NUMBER(5,0) NOT NULL, -- 방번호,
	USER_ID VARCHAR2(20) NOT NULL, -- 아이디,
	ROOM_NAME VARCHAR2(20) NOT NULL, -- 방이름,
	MAX_CAPACITY NUMBER(3,0) NOT NULL, -- 수용인원,
	ROOM_COUNT NUMBER(2,0) NOT NULL, -- 방개수,
	BED_COUNT NUMBER(2,0) NOT NULL, -- 침대,
	ROOM_PRICE NUMBER(10,0) NOT NULL, -- 가격,
	CITY VARCHAR2(10) NOT NULL, -- 지역,
	EXPLANATION VARCHAR(200) NULL -- 설명
);

-- 방
ALTER TABLE ROOM
	ADD CONSTRAINT PK_ROOM -- 방 기본키
	PRIMARY KEY (
		ROOM_NUMBER -- 방번호
	);

-- 렌트카
CREATE TABLE CAR (
	CAR_NUMBER VARCHAR2(10) NOT NULL, -- 차번호,
	USER_ID VARCHAR2(20) NOT NULL, -- 아이디,
	CAR_KIND VARCHAR2(20) NOT NULL, -- 차종류,
	CAR_PRICE NUMBER(10,0) NOT NULL, -- 가격,
	CAR_SEATS NUMBER(2,0) NOT NULL, -- 인승,
	CITY VARCHAR2(10) NOT NULL, -- 지역,
	CAR_COLOR VARCHAR2(20) NULL -- 차색상
);

-- 렌트카
ALTER TABLE CAR
	ADD CONSTRAINT PK_CAR -- 렌트카 기본키
	PRIMARY KEY (
		CAR_NUMBER -- 차번호
	);

-- 관광명소
CREATE TABLE TOUR (
	TOUR_NUMBER NUMBER(5,0) NOT NULL, -- 투어번호,
	USER_ID VARCHAR2(20) NOT NULL, -- 아이디,
	TOUR_NAME VARCHAR2(20) NOT NULL, -- 이름,
	TOUR_TIME VARCHAR2(10) NOT NULL, -- 투어시간,
	TOUR_PRICE NUMBER(10,0) NOT NULL, -- 가격,
	CITY VARCHAR2(10) NOT NULL, -- 지역,
	EXPLANATION VARCHAR2(100) NULL -- 설명
);

-- 관광명소
ALTER TABLE TOUR
	ADD CONSTRAINT PK_TOUR -- 관광명소 기본키
	PRIMARY KEY (
		TOUR_NUMBER -- 투어번호
	);

-- 패키지
CREATE TABLE PACK (
	PACK_NUM NUMBER(5,0) NOT NULL, -- 패키지번호,
	TOUR_NUMBER NUMBER(5,0) NOT NULL, -- 투어번호,
	ROOM_NUMBER NUMBER(5,0) NOT NULL, -- 방번호,
	CAR_NUMBER VARCHAR2(10) NOT NULL, -- 차번호,
	SALE_RATE NUMBER(10,0) NOT NULL -- 할인가격
);

-- 패키지
ALTER TABLE PACK
	ADD CONSTRAINT PK_PACK -- 패키지 기본키
	PRIMARY KEY (
		PACK_NUM -- 패키지번호
	);

-- 결제
CREATE TABLE PAYMENT (
	CART_NO NUMBER(5,0) NOT NULL, -- 결제번호,
	USER_ID VARCHAR2(20) NOT NULL, -- 아이디,
	PACK_NUM NUMBER(5,0) NOT NULL, -- 패키지번호,
	START_DATE DATE NOT NULL, -- 시작날짜,
	END_DATE DATE NOT NULL, -- 종료날짜,
	PEOPLE NUMBER(3,0) NOT NULL, -- 인원수,
	PAY_DATE DATE NOT NULL, -- 결제날짜,
	REFUND CHAR(1) NOT NULL -- 환불여부
);

-- 결제
ALTER TABLE PAYMENT
	ADD CONSTRAINT PK_PAYMENT -- 결제 기본키
	PRIMARY KEY (
		CART_NO -- 결제번호
	);

-- 방
ALTER TABLE ROOM
	ADD CONSTRAINT FK_OUTERPARK_USER_TO_ROOM -- 사용자 -> 방
	FOREIGN KEY (
		USER_ID -- 아이디
	)
	REFERENCES OUTERPARK_USER ( -- 사용자
		USER_ID -- 아이디
	);

-- 렌트카
ALTER TABLE CAR
	ADD CONSTRAINT FK_OUTERPARK_USER_TO_CAR -- 사용자 -> 렌트카
	FOREIGN KEY (
		USER_ID -- 아이디
	)
	REFERENCES OUTERPARK_USER ( -- 사용자
		USER_ID -- 아이디
	);

-- 관광명소
ALTER TABLE TOUR
	ADD CONSTRAINT FK_OUTERPARK_USER_TO_TOUR -- 사용자 -> 관광명소
	FOREIGN KEY (
		USER_ID -- 아이디
	)
	REFERENCES OUTERPARK_USER ( -- 사용자
		USER_ID -- 아이디
	);

-- 패키지
ALTER TABLE PACK
	ADD CONSTRAINT FK_ROOM_TO_PACK -- 방 -> 패키지
	FOREIGN KEY (
		ROOM_NUMBER -- 방번호
	)
	REFERENCES ROOM ( -- 방
		ROOM_NUMBER -- 방번호
	);

-- 패키지
ALTER TABLE PACK
	ADD CONSTRAINT FK_TOUR_TO_PACK -- 관광명소 -> 패키지
	FOREIGN KEY (
		TOUR_NUMBER -- 투어번호
	)
	REFERENCES TOUR ( -- 관광명소
		TOUR_NUMBER -- 투어번호
	);

-- 패키지
ALTER TABLE PACK
	ADD CONSTRAINT FK_CAR_TO_PACK -- 렌트카 -> 패키지
	FOREIGN KEY (
		CAR_NUMBER -- 차번호
	)
	REFERENCES CAR ( -- 렌트카
		CAR_NUMBER -- 차번호
	);

-- 결제
ALTER TABLE PAYMENT
	ADD CONSTRAINT FK_PACK_TO_PAYMENT -- 패키지 -> 결제
	FOREIGN KEY (
		PACK_NUM -- 패키지번호
	)
	REFERENCES PACK ( -- 패키지
		PACK_NUM -- 패키지번호
	);

-- 결제
ALTER TABLE PAYMENT
	ADD CONSTRAINT FK_OUTERPARK_USER_TO_PAYMENT -- 사용자 -> 결제
	FOREIGN KEY (
		USER_ID -- 아이디
	)
	REFERENCES OUTERPARK_USER ( -- 사용자
		USER_ID -- 아이디
	);
	

	INSERT INTO OUTERPARK_USER 
	VALUES ();
	
	SELECT * FROM OUTERPARK_USER WHERE USER_ID = 'show5116' AND USER_PASSWORD = 'show5116'; 
	SELECT * FROM OUTERPARK_USER;
	
SELECT * FROM OUTERPARK_USER WHERE ID = 'yoo';

COMMIT;


SELECT ROOM_NUMBER
  FROM ROOM R, PACK P, PAYMENT Y
 WHERE R.ROOM_NUMBER = P.ROOM_NUMBER
   AND Y.PACK_NUM = P.PACK_NUMBER
   AND ? NOT IN(SELECT YMD 
		         FROM(SELECT TO_DATE (START_DATE, 'YYYYMMDD')+(LEVEL - 1) YMD
				        FROM PAYMENT
				       WHERE PAY_DATE IS NOT NULL
			         CONNECT BY TO_DATE (START_DATE, 'YYYYMMDD')+(LEVEL-1) <= END_DATE));
			        
UPDATE OUTERPARK_USER SET USER_PASSWORD = 'aaa' WHERE USER_ID = 'show5116' AND USER_MAIL = 'show5116@naver.com' AND USER_NICKNAME = '퐁퐁이';
COMMIT;  

CREATE SEQUENCE SEQ_PACK
    START WITH 1
    INCREMENT BY 1;
   
CREATE SEQUENCE SEQ_ROOM
    START WITH 1
    INCREMENT BY 1;
   
CREATE SEQUENCE SEQ_TOUR
    START WITH 1
    INCREMENT BY 1;
   
CREATE SEQUENCE SEQ_PAYMENT
    START WITH 1
    INCREMENT BY 1;

COMMIT;
INSERT INTO ROOM VALUES (SEQ_ROOM.NEXTVAL,'show5116','씨뷰스위트호텔',4 ,2, 2, 100000, '부산','바다가 보이는 쾌적한 방입니다.');

SELECT C.CAR_KIND,
	   C.CAR_SEATS,
	   C.CAR_COLOR 
  FROM PAYMENT PAY,PACK PAC,CAR C
 WHERE PAY.PACK_NUMBER = PAC.PACK_NUMBER 
   AND PAC.CAR_NUMBER = C.CAR_NUMBER 
   AND PAY.CART_NUMBER = 9;
  
SELECT T.TOUR_NAME ,
	   T.TOUR_TIME ,
	   T.EXPLANATION 
  FROM PAYMENT PAY,PACK PAC,TOUR T
 WHERE PAY.PACK_NUMBER = PAC.PACK_NUMBER 
   AND PAC.TOUR_NUMBER = T.TOUR_NUMBER 
   AND PAY.CART_NUMBER = 9;
  
SELECT R.ROOM_NAME ,
	   R.ROOM_COUNT ,
	   R.BED_COUNT ,
	   R.MAX_CAPACITY ,
	   R.EXPLANATION 
  FROM PAYMENT PAY,PACK PAC,ROOM R
 WHERE PAY.PACK_NUMBER = PAC.PACK_NUMBER 
   AND PAC.ROOM_NUMBER = R.ROOM_NUMBER 
   AND PAY.CART_NUMBER = 9;
  
SELECT R.CITY ,
	   PAC.PEOPLE ,
	   R.BED_COUNT ,
	   R.MAX_CAPACITY ,
	   R.EXPLANATION 
  FROM PAYMENT PAY,PACK PAC,ROOM R
 WHERE PAY.PACK_NUMBER = PAC.PACK_NUMBER 
   AND PAC.ROOM_NUMBER = R.ROOM_NUMBER 
   AND PAY.CART_NUMBER = 9;


  


















